### ISSUE TITLE
When a note is updated

### ISSUE THREAD

**Issue by Chiranjit34** [Chiranjit34/NotesApp#1]
When a note is updated it should be marked as updated.

**Comment by IrfanSalim** [comment]
Hey, can I take this up

**Comment by Chiranjit34** [comment]
Hey Md Irfan Salim, sure you can take this up. Create a new branch and push
your code to that new branch.

**Comment by IrfanSalim** [comment]
Hey, @Chiranjit34 

I'm unable to start the client, getting the below error. Any suggestions?

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:386:16)
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:418:10
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\webpack\lib\NormalModule.js:293:13
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\irfan\OneDrive\Desktop\Projects\NotesApp\client\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by Chiranjit34** [comment]
You are using the node 18 version. Try using node 16. It will work.
